import tkinter as tk
win=tk.Tk()
win.title("CALCULATOR")
win.geometry("400x350")
def buttonclick(label):
    h.insert("end",label)
def clearbutton():
    h.delete(0,'end')
def backspace():
    text = h.get()
    h.delete(0, "end")
    h.insert(0, text[:-1])
def calculate():
    try:
        result = eval(h.get())
        h.delete(0, "end")
        h.insert(0, result)
    except:
        h.delete(0, "end")
        h.insert(0, "Error")    
h=tk.Entry(win,font=("Arial",22,"bold"),width=23,bd=10,bg=
           "skyblue",justify="right")
h.grid(row=1,column=1,columnspan=4)
k7=tk.Button(win,text="7",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("7"))
k7.grid(row=2,column=1)
k8=tk.Button(win,text="8",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("8"))
k8.grid(row=2,column=2)
k9=tk.Button(win,text="9",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("9"))
k9.grid(row=2,column=3)
k4=tk.Button(win,text="4",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("4"))
k4.grid(row=3,column=1)
k5=tk.Button(win,text="5",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("5"))
k5.grid(row=3,column=2)
k6=tk.Button(win,text="6",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("6"))
k6.grid(row=3,column=3)
k1=tk.Button(win,text="1",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("1"))
k1.grid(row=4,column=1)
k2=tk.Button(win,text="2",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("2"))
k2.grid(row=4,column=2)
k3=tk.Button(win,text="3",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("3"))
k3.grid(row=4,column=3)
ka=tk.Button(win,text="+",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("+"))
ka.grid(row=2,column=4)
kb=tk.Button(win,text="-",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("-"))
kb.grid(row=3,column=4)
kc=tk.Button(win,text="*",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("*"))
kc.grid(row=4,column=4)
kd=tk.Button(win,text="/",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("/"))
kd.grid(row=5,column=4)
ke=tk.Button(win,text="AC",font=("Arial",16,"bold")
,height=2,width=4,command=clearbutton)
ke.grid(row=5,column=1)
kf=tk.Button(win,text="0",font=("Arial",16,"bold")
,height=2,width=4,command=lambda:buttonclick("0"))
kf.grid(row=5,column=2)
kg=tk.Button(win,text="=",font=("Arial",16,"bold")
,height=2,width=4,command=calculate)
kg.grid(row=5,column=3)
win.mainloop()

